  [[blocks.segments]]
    template = ' <b>  {{if eq .Output "0"}}loaded{{else if eq .Output "1"}}not loaded{{else}}denied{{ end }}</b>'
    foreground = 'white'
    foreground_templates = [
      '{{if eq .Output "0"}}green{{end}}',
      '{{if eq .Output "1"}}cyan{{end}}',
      '{{if eq .Output "2"}}red{{end}}'
    ]
    background = 'transparent'
    type = 'command'
    style = 'plain'

    [blocks.segments.properties]
      shell = 'bash'
      script = '~/.config/ohmyposh/direnv.sh'

