  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#4e9a06'
    background = 'transparent'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}',
      '{{ if gt .Ahead 0 }}#89d1dc{{ end }}',
      '{{ if gt .Behind 0 }}#4e9a06{{ end }}'
    ]

    syle = 'plain'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

