general.import = [
  "themes/catppuccin-mocha.toml"
]

[env]
# for ssh, i set this in .zshrc
# TERM = "xterm-256color"
# LANG = "de_DE.UTF-8"
# LC_CTYPE = "de_DE.UTF-8"

[window]
# decorations = "None"

# These configs are dependent from another
# startup_mode = "Fullscreen"
# startup_mode = "Maximized"
position = { x = 500, y = 250 }
dimensions = { columns = 160, lines = 40 }

[font]
size = 12

[font.normal]
family = "jetbrains mono"

