services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PGADMIN_DEFAULT_EMAIL: "1@1.com"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_DEFAULT_PASSWORD"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.localhost`)"
      - "traefik.http.routers.dozzle.entrypoints=web"

  traefik:
    image: traefik:latest
    container_name: traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:80:80/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  pgadmin_data:
  postgres_data:
