services:
  traefik:
    image: traefik:latest
    container_name: traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:80:80/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

